version: "3.5"

services:
  front:
    image: nginx:1.17-alpine
    volumes:
      - ./front:/usr/share/nginx/html:ro
    networks:
      - nizhib
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:portrait.nizhib.ai

  back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:portrait.nizhib.ai;PathPrefix:/api;PathPrefixStrip:/api

networks:
  nizhib:
    name: nizhib
    driver: bridge
